#!/bin/bash
name=$USER

echo "cd into $name directory"
cd /home/$name/

echo "step №1 creating a specific amount of directories"
mkdir -p homework/dir-0{1..4}

echo "step №2 creating a specific amount of files in dirictories"
touch homework/dir-0{1..4}/file-{1..4}

echo "step №3 cd into $name directory"
cd /home/$name/homework

echo "step №4 filling the script"
cat << _EOF_ > dir-01/file-2
#!/bin/bash
echo "Hello $name!
The End."
_EOF_

echo "step №5 make file-2 executable"
chmod 755 dir-01/file-2

echo "step №6 running the script"
bash dir-01/file-2

